### ISSUE TITLE
Case-Insensitive Import Collision

### ISSUE THREAD

**Issue by robintemme** [neko-neko/echo-logrus#3]
Hey there, thanks a lot for your work.

I was just starting to use it, when this error occurred:
`case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"`

You used the capitalized name in your [code](https://github.com/neko-neko/echo-logrus/blob/7b8077a1feaef9a9e7cb3eefb98fe2cdc275005b/log/log.go#L8). Is there a specific reason or could you simply change it?

**Comment by neko-neko** [comment]
@zwerch Hi, thank you for your issue report.
> Is there a specific reason or could you simply change it?

I wrong uppercase of package name, it can be simply change.
I'd like to merge [your fix](https://github.com/zwerch/echo-logrus/pull/1), please send me PR:smile:

**Comment by neko-neko** [comment]
@zwerch Thank you to send PR!
I merged your PR and release [new version](https://github.com/neko-neko/echo-logrus/releases/tag/v1.0.3).
